modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="tfc_ie_addon"
version="${file.jarVersion}"
displayName="TFC + IE Crossover"
logoFile="logo.png"
credits="Thanks to Developers of such wonderful mods as TerraFirmaCraft: TNG and Immersive Engineering.\nEspecially to EERussianguy, whose addon FirmaLife was used as base for this addon.\nSome textures of BluSunrize were used or modified.\nAlso, were used some textures from TFC: TNG, all credits to the developers."
authors="NMagpie"
description="Addon to make TFC and IE compatible."

[[dependencies.tfc_ie_addon]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tfc_ie_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tfc_ie_addon]]
    modId="tfc"
    mandatory=true
    versionRange="[1.18.2-2.2.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tfc_ie_addon]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[1.18.2-8.3.0-155.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tfc_ie_addon]]
modId="jei"
mandatory=false
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"